# - Try to find libwebsockets API
# Once done this will define
#  
#  LIBWEBSOCKETS_FOUND        - System has the libwebsockets API
#  LIBWEBSOCKETS_INCLUDE_DIRS - The APIs include directory
#  LIBWEBSOCKETS_LIBRARY_DIR  - The APIs library directory
#  LIBWEBSOCKETS_LIBRARIES    - Link these to use the API
#   

IF (LIBWEBSOCKETS_FOUND)
    # Already in cache, be silent
    SET(LIBWEBSOCKETS_FIND_QUIETLY TRUE)
ENDIF (LIBWEBSOCKETS_FOUND)

if( WIN32 )
    FIND_PATH( LIBWEBSOCKETS_INCLUDE_DIRS libwebsockets.h
        PATHS "C:/libwinsockets/include")
    SET( LIBWEBSOCKETS_NAMES libwebsocketswin32 )
    FIND_LIBRARY( LIBWEBSOCKETS_LIBRARIES
        NAMES ${LIBWEBSOCKETS_NAMES}
        PATHS "C:/libwinsockets/lib")


    GET_FILENAME_COMPONENT( LIBWEBSOCKETS_LIBRARY_DIR ${LIBWEBSOCKETS_LIBRARIES} PATH )

    IF (LIBWEBSOCKETS_INCLUDE_DIRS AND LIBWEBSOCKETS_LIBRARIES)
        SET(LIBWEBSOCKETS_FOUND TRUE)
    ELSE (LIBWEBSOCKETS_INCLUDE_DIRS AND LIBWEBSOCKETS_LIBRARIES)
        SET( LIBWEBSOCKETS_FOUND FALSE )
        SET( LIBWEBSOCKETS_LIBRARY_DIR )
    ENDIF (LIBWEBSOCKETS_INCLUDE_DIRS AND LIBWEBSOCKETS_LIBRARIES)

    MARK_AS_ADVANCED(
        LIBWEBSOCKETS_LIBRARY
        LIBWEBSOCKETS_LIBRARIES
        LIBWEBSOCKETS_INCLUDE_DIRS
        )

else( WIN32 )
    message(ERROR "libwebsockets cmake find not written for this OS yet")
endif( WIN32 )
